export const units = [
  ["Let's be friends!", "让我们成为朋友！", "Friends · 朋友", "mint", "🤝"],
  [
    "My school things",
    "我的学习用品",
    "School things · 学习用品",
    "sand",
    "🎒",
  ],
  [
    "It's a colourful world!",
    "五彩缤纷的世界！",
    "Colours · 色彩",
    "pink",
    "🌈",
  ],
  ["Fun with numbers", "数字的乐趣", "Numbers · 数字", "blue", "🔢"],
  ["We're family", "我们是一家人", "Family · 家人", "peach", "🏡"],
  ["My sweet home", "我甜蜜的家", "Home · 家", "lilac", "🪴"],
];
const card = (en, zh, note, noteZh) => ({ en, zh, note, noteZh });
const q = (
  id,
  prompt,
  zh,
  options,
  answer,
  explain,
  explainZh,
  word = "",
  audio = "",
) => ({ id, prompt, zh, options, answer, explain, explainZh, word, audio });
export const lessons = [
  {
    id: "hello",
    title: "Hello, new friends!",
    zh: "你好，新朋友！",
    type: "Learn · 学习",
    minutes: 4,
    icon: "👋",
    intro: "Start with a greeting. Listen, then say it aloud.",
    introZh: "先打个招呼。听一听，再大声说出来。",
    cards: [
      card(
        "Hello!",
        "你好！",
        "Say hello when you meet someone.",
        "见面时可以说 Hello 或 Hi。",
      ),
      card(
        "Nice to meet you.",
        "很高兴认识你。",
        "Use this when meeting a new friend.",
        "初次认识新朋友时可以这样说。",
      ),
      card(
        "Let's be friends!",
        "让我们成为朋友！",
        "Let's means let us.",
        "Let’s 是 let us 的缩写。",
      ),
      card(
        "Let's play together.",
        "让我们一起玩吧。",
        "A friendly invitation.",
        "用这句话邀请朋友一起玩。",
      ),
    ],
    questions: [
      q(
        "greet",
        "You meet a new friend. What do you say?",
        "你遇到一位新朋友。你会说什么？",
        ["Nice to meet you.", "Goodbye.", "Sit down."],
        0,
        "Nice to meet you is a friendly greeting.",
        "Nice to meet you 是初次见面的友好问候。",
        "meet",
      ),
    ],
  },
  {
    id: "words",
    title: "Our friendship words",
    zh: "我们的朋友词汇",
    type: "Words · 单词",
    minutes: 5,
    icon: "🤝",
    wordTexts: [
      "friend",
      "meet",
      "happy",
      "new",
      "play",
      "help",
      "together",
      "nine",
    ],
    intro: "Explore eight useful words. Tap each speaker and read the example.",
    introZh: "学习八个实用单词。点击播放，读一读例句。",
    cards: [],
    questions: [
      q(
        "friend-meaning",
        "Which word means 朋友?",
        "哪个单词的意思是“朋友”？",
        ["friend", "school", "book"],
        0,
        "A friend is someone you enjoy being with.",
        "friend 表示朋友。",
        "friend",
      ),
      q(
        "help-meaning",
        "Which word means 帮助?",
        "哪个单词的意思是“帮助”？",
        ["play", "help", "nine"],
        1,
        "Let's help means 让我们帮忙吧。",
        "帮助朋友是一件友善的事。",
        "help",
      ),
    ],
  },
  {
    id: "introduce",
    title: "This is me",
    zh: "介绍我自己",
    type: "Learn · 学习",
    minutes: 5,
    icon: "🌱",
    intro: "Say your name, age, and where you are from.",
    introZh: "说说你的名字、年龄和来自哪里。",
    cards: [
      card(
        "I'm Sam.",
        "我是萨姆。",
        "I'm is short for I am.",
        "I’m 是 I am 的缩写。",
      ),
      card(
        "I'm nine.",
        "我九岁。",
        "Use a number to tell your age.",
        "用数字表达你的年龄。",
      ),
      card(
        "I'm from China.",
        "我来自中国。",
        "Use from before a country.",
        "在国家名称前使用 from。",
      ),
      card(
        "We're from the UK.",
        "我们来自英国。",
        "We're means we are. Sam and Amy are from the UK.",
        "We’re 表示 we are。萨姆和埃米来自英国。",
      ),
    ],
    questions: [
      q(
        "age",
        "How does Sam tell his age?",
        "萨姆怎样表达自己的年龄？",
        ["I'm nine.", "I'm Sam.", "I'm from China."],
        0,
        "I'm nine tells us his age.",
        "I’m nine 表示他九岁。",
        "nine",
      ),
      q(
        "from",
        "Complete: I am ___ China.",
        "填空：I am ___ China.",
        ["from", "nine", "she"],
        0,
        "Use from to say where you are from.",
        "用 from 表示来自哪里。",
        "from",
      ),
    ],
  },
  {
    id: "friends",
    title: "Meet my friends",
    zh: "认识我的朋友",
    type: "Listen · 听力",
    minutes: 5,
    icon: "🎧",
    intro: "Learn he, she, and we. Then listen carefully to choose an answer.",
    introZh: "学习 he、she 和 we，然后仔细听音选择答案。",
    cards: [
      card(
        "She's Amy.",
        "她是埃米。",
        "She's means she is.",
        "She’s 表示 she is，用于介绍她。",
      ),
      card(
        "He's Sam.",
        "他是萨姆。",
        "He's means he is.",
        "He’s 表示 he is，用于介绍他。",
      ),
      card(
        "We're friends.",
        "我们是朋友。",
        "We're means we are.",
        "We’re 表示 we are，用于说我们。",
      ),
    ],
    questions: [
      q(
        "hear-she",
        "Listen. Who is speaking about Amy?",
        "听一听，选择你听到的句子。",
        ["She's Amy.", "He's Sam.", "We're friends."],
        0,
        "She's Amy means 她是埃米。",
        "She 用于指她。",
        "she",
        "She's Amy.",
      ),
      q(
        "hear-we",
        "Listen and choose.",
        "听音并选择。",
        ["I'm nine.", "We're friends.", "He's Sam."],
        1,
        "We're friends means 我们是朋友。",
        "We 用于指我们。",
        "we",
        "We're friends.",
      ),
    ],
  },
  {
    id: "repeat",
    title: "Your turn to speak",
    zh: "轮到你说啦",
    type: "Repeat · 跟读",
    minutes: 4,
    icon: "💬",
    intro: "Listen, pause, and repeat aloud. No microphone is needed.",
    introZh: "听一听，停一停，再大声跟读。无需麦克风。",
    cards: [
      card(
        "Hello! Nice to meet you.",
        "你好！很高兴认识你。",
        "Imagine meeting a new friend.",
        "想象你遇到了一位新朋友。",
      ),
      card(
        "I'm Sam. I'm nine.",
        "我是萨姆。我九岁。",
        "Now say your own name and age aloud.",
        "现在大声说出你自己的名字和年龄。",
      ),
      card(
        "She's my friend. We're friends.",
        "她是我的朋友。我们是朋友。",
        "Try introducing a friend.",
        "试着介绍一位朋友。",
      ),
      card(
        "Thank you!",
        "谢谢你！",
        "Say this when someone helps you.",
        "别人帮助你时，说声谢谢。",
      ),
    ],
    questions: [],
  },
  {
    id: "story",
    title: "A little help, a new friend",
    zh: "小小帮助，新的朋友",
    type: "Story · 故事",
    minutes: 6,
    icon: "🪁",
    intro:
      "An adapted retelling of the Unit 1 kite story. Read one scene at a time.",
    introZh: "根据第一单元风筝故事改编。一次读一个场景。",
    cards: [
      card(
        "Oh, no!",
        "噢，不！",
        "Ben's kite is stuck in a tree. David and Mia see him.",
        "本的风筝挂在树上了。戴维和米娅看到了他。",
      ),
      card(
        "Let's help. Here you are.",
        "让我们帮忙吧。给你。",
        "David and Mia help Ben get his kite back.",
        "戴维和米娅帮本拿回了风筝。",
      ),
      card(
        "Thank you! I'm Ben.",
        "谢谢你们！我是本。",
        "Ben thanks his new friends. Mia introduces David.",
        "本感谢新朋友。米娅介绍了戴维。",
      ),
      card(
        "We're nine. Let's play together!",
        "我们九岁。让我们一起玩吧！",
        "The three children become friends and play together.",
        "三个孩子成为朋友，一起玩耍。",
      ),
    ],
    questions: [
      q(
        "story-help",
        "What do David and Mia do?",
        "戴维和米娅做了什么？",
        ["Help Ben.", "Hide the kite.", "Go home."],
        0,
        "They help Ben get his kite back.",
        "他们帮本拿回风筝。",
        "help",
      ),
      q(
        "story-thanks",
        "What does Ben say after they help?",
        "得到帮助后，本说了什么？",
        ["Goodbye.", "Thank you!", "No!"],
        1,
        "We say thank you when someone helps us.",
        "别人帮助我们时，要说谢谢。",
        "thank",
      ),
    ],
  },
  {
    id: "alphabet",
    title: "Meet the alphabet",
    zh: "认识英文字母",
    type: "Explore · 探索",
    minutes: 5,
    icon: "Aa",
    intro:
      "Tap a letter to hear its US letter name. Uppercase and lowercase are partners.",
    introZh: "点击字母，听美式字母名称。大写和小写是一对伙伴。",
    cards: [],
    questions: [
      q(
        "letter-a",
        "Which is the lowercase form of A?",
        "A 对应的小写字母是哪个？",
        ["a", "b", "d"],
        0,
        "A and a are the same letter in two forms.",
        "A 和 a 是同一个字母的大小写形式。",
      ),
      q(
        "letter-d",
        "Which letter comes after C?",
        "C 后面是哪个字母？",
        ["B", "D", "G"],
        1,
        "The order is A, B, C, D.",
        "字母顺序是 A、B、C、D。",
      ),
    ],
  },
  {
    id: "kindness",
    title: "Be a good friend",
    zh: "做一个好朋友",
    type: "Explore · 探索",
    minutes: 4,
    icon: "💛",
    intro:
      "A good friend listens, shares, helps, and plays with you. Choose one kind thing to do today.",
    introZh: "好朋友会倾听、分享、帮助和陪伴。选择一件今天可以做的友善小事。",
    cards: [
      card(
        "Listen to your friend.",
        "听朋友说话。",
        "Give your friend time to speak.",
        "给朋友说话的时间，认真倾听。",
      ),
      card(
        "Let's share the apple.",
        "让我们分享这个苹果。",
        "Sharing can make a friend happy.",
        "分享可以让朋友开心。",
      ),
      card(
        "Let's help.",
        "让我们帮忙吧。",
        "Notice when a friend needs help.",
        "留意朋友是否需要帮助。",
      ),
      card(
        "Play with me.",
        "和我一起玩。",
        "Invite someone to join your game.",
        "邀请别人一起玩游戏。",
      ),
    ],
    questions: [
      q(
        "kind-listen",
        "Your friend is talking. What can you do?",
        "朋友正在说话，你可以怎么做？",
        ["Listen.", "Shout.", "Walk away."],
        0,
        "A good friend listens.",
        "好朋友会认真倾听。",
        "listen",
      ),
      q(
        "kind-share",
        "You have a toy. Your friend wants to play too.",
        "你有一个玩具，朋友也想玩。",
        ["Hide it.", "Share and play together.", "Say no every time."],
        1,
        "Sharing and playing together are kind choices.",
        "分享和一起玩都是友善的选择。",
        "play",
      ),
    ],
  },
  {
    id: "project",
    title: "My friends postcard",
    zh: "我的朋友明信片",
    type: "Create · 创作",
    minutes: 5,
    icon: "🎨",
    intro:
      "Create a little postcard about a real or imaginary friend. Save it and read it aloud.",
    introZh: "为真实或想象中的朋友制作一张明信片，保存后大声读出来。",
    cards: [],
    questions: [],
  },
  {
    id: "review",
    title: "Look how much you know!",
    zh: "看看你学会了多少！",
    type: "Review · 复习",
    minutes: 5,
    icon: "⭐",
    intro:
      "Try these questions on your own. Mistakes help us choose what to review next.",
    introZh: "试着独立答题。做错的题会帮助我们安排下次复习。",
    cards: [],
    questions: [
      q(
        "review-hello",
        "Choose a friendly greeting.",
        "选择一句友好的问候。",
        ["Hello!", "No!", "Close the book."],
        0,
        "Hello is a greeting.",
        "Hello 用于打招呼。",
        "hello",
      ),
      q(
        "review-she",
        "Complete: ___ is Amy.",
        "填空：___ is Amy.",
        ["He", "She", "We"],
        1,
        "She is Amy.",
        "她是埃米。",
        "she",
      ),
      q(
        "review-we",
        "Complete: We ___ friends.",
        "填空：We ___ friends.",
        ["am", "is", "are"],
        2,
        "We goes with are.",
        "We 与 are 搭配。",
        "we",
      ),
      q(
        "review-nine",
        "Listen and choose the number.",
        "听音，选择数字。",
        ["5", "9", "3"],
        1,
        "Nine is 9.",
        "nine 表示九。",
        "nine",
        "nine",
      ),
      q(
        "review-help",
        "Your friend needs help. What can you say?",
        "你的朋友需要帮助，你可以说什么？",
        ["Let's help.", "Goodbye.", "Oh, no."],
        0,
        "Let's help is a kind response.",
        "Let’s help 是友善的回应。",
        "help",
      ),
      q(
        "review-friend",
        "Build the sentence.",
        "选择正确的句子。",
        ["I'm friend my.", "She is my friend.", "We is friends."],
        1,
        "She is my friend.",
        "她是我的朋友。",
        "friend",
      ),
    ],
  },
];
export const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
export const letterNames = [
  "ay",
  "bee",
  "see",
  "dee",
  "ee",
  "ef",
  "gee",
  "aitch",
  "eye",
  "jay",
  "kay",
  "el",
  "em",
  "en",
  "oh",
  "pee",
  "cue",
  "ar",
  "ess",
  "tee",
  "you",
  "vee",
  "double you",
  "ex",
  "why",
  "zee",
];
