// Individual sound recordings, not example words. Streamed from the publisher.
// Source: https://dictionary.cambridge.org/help/phonetics.html (checked 2026-09-07).
// Cambridge writes our /ɝ/ as /ɝː/ and our /ɡ/ as /g/.
export const phoneticAudio = {
  iː: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_sheep_2023feb.mp3",
  ɪ: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_ship_2023feb.mp3",
  e: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_head_2023feb.mp3",
  æ: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_hat_2023feb.mp3",
  ɑː: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_father_2023feb.mp3",
  ɔː: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_horse_2023feb.mp3",
  ʊ: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_foot_2023feb.mp3",
  uː: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_blue_2023feb.mp3",
  ʌ: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_cup_2023feb.mp3",
  ə: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_above_2023feb.mp3",
  ɝ: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_bird_2023feb.mp3",
  ɚ: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_mother_2023feb.mp3",
  eɪ: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_day_2023feb_002.mp3",
  aɪ: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_eye_2023feb.mp3",
  ɔɪ: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_boy_2023feb.mp3",
  aʊ: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_mouth_2023feb.mp3",
  oʊ: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_nose_2023feb.mp3",
  p: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_pen_2023feb.mp3",
  b: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_book_2023feb.mp3",
  t: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_town_2023feb.mp3",
  d: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_day_2023feb_001.mp3",
  k: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_cat_2023feb.mp3",
  ɡ: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_give_2023feb.mp3",
  f: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_fish_2023feb.mp3",
  v: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_very_2023feb.mp3",
  θ: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_think_2023feb.mp3",
  ð: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_this_2023feb.mp3",
  s: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_say_2023feb.mp3",
  z: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_zoo_2023feb.mp3",
  ʃ: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_she_2023feb.mp3",
  ʒ: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_vision_2023feb.mp3",
  h: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_hand_2023feb.mp3",
  tʃ: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_cheese_2023feb.mp3",
  dʒ: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_jump_2023feb.mp3",
  m: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_moon_2023feb.mp3",
  n: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_name_2023feb.mp3",
  ŋ: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_sing_2023feb.mp3",
  l: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_look_2023feb.mp3",
  r: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_run_2023feb.mp3",
  j: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_yes_2023feb.mp3",
  w: "https://dictionary.cambridge.org/media/english/us_phonetic/us_phonetics_sound_we_2023feb.mp3",
  ɒ: "https://dictionary.cambridge.org/media/english/uk_phonetic/uk_phonetics_sound_sock_2023feb.mp3",
  ɜː: "https://dictionary.cambridge.org/media/english/uk_phonetic/uk_phonetics_sound_bird_2023feb.mp3",
  əʊ: "https://dictionary.cambridge.org/media/english/uk_phonetic/uk_phonetics_sound_nose_2023feb.mp3",
  ɪə: "https://dictionary.cambridge.org/media/english/uk_phonetic/uk_phonetics_sound_ear_2023feb.mp3",
  eə: "https://dictionary.cambridge.org/media/english/uk_phonetic/uk_phonetics_sound_hair_2023feb.mp3",
  ʊə: "https://dictionary.cambridge.org/media/english/uk_phonetic/uk_phonetics_sound_pure_2023feb.mp3",
};
